# Generated by Django 5.1.1 on 2024-09-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discountid', models.IntegerField(db_column='discountId', primary_key=True, serialize=False)),
                ('discountprice', models.DecimalField(db_column='discountPrice', decimal_places=2, max_digits=6)),
                ('discountreason', models.TextField(db_column='discountReason')),
                ('resolveddate', models.DateTimeField(db_column='resolvedDate')),
            ],
            options={
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('furnitureid', models.IntegerField(db_column='furnitureId', primary_key=True, serialize=False)),
                ('furniturecategory', models.CharField(db_column='furnitureCategory', max_length=20)),
                ('furnituretype', models.CharField(db_column='furnitureType', max_length=20)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discountedprice', models.DecimalField(blank=True, db_column='discountedPrice', decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'furniture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.IntegerField(db_column='locationId', primary_key=True, serialize=False)),
                ('locationtype', models.CharField(db_column='locationType', max_length=15)),
                ('name', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'location',
                'db_table_comment': 'Location table contains details of the store/warehouse locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketid', models.IntegerField(db_column='ticketId', primary_key=True, serialize=False)),
                ('issuestatus', models.CharField(db_column='issueStatus', max_length=25)),
                ('createddate', models.DateTimeField(db_column='createdDate')),
                ('issuedescription', models.TextField(db_column='issueDescription')),
                ('resolutiontype', models.CharField(blank=True, db_column='resolutionType', max_length=45, null=True)),
                ('resolutioncomments', models.TextField(blank=True, db_column='resolutionComments', null=True)),
                ('resolutiondate', models.DateTimeField(blank=True, db_column='resolutionDate', null=True)),
                ('lastupdateddate', models.DateTimeField(blank=True, db_column='lastUpdatedDate', null=True)),
            ],
            options={
                'db_table': 'ticket',
                'db_table_comment': 'Table to maintain all the ticket data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticketimage',
            fields=[
                ('imageid', models.IntegerField(db_column='imageId', primary_key=True, serialize=False)),
                ('imagecontent', models.TextField(db_column='imageContent')),
                ('uploaddate', models.DateTimeField(db_column='uploadDate')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticketImage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=45)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=45, null=True)),
                ('usertype', models.CharField(db_column='userType', max_length=10)),
                ('status', models.CharField(max_length=1)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
